import type { WorkRecord } from "@/lib/contract";

// The verified record. This is the only text visitors ever see; the model only
// picks facet ids from it. Every line is true, in the owner's words where
// available, and backed by a public link wherever one exists.
//
// Sources: the owner's verified facts, the V1 site content at tag v1.0, public
// GitHub repo descriptions under github.com/Kart-ing, and Devpost taglines
// quoted verbatim. Never add a date of birth, age, immigration status, phone
// number, street address or GPA.
//
// V3 metadata (start, stack, repo, media) is verified from each star's period,
// the karts repo's first commit, Kart-ing repo creation dates, languages and
// READMEs, and the owner's own project images on public Devpost pages.

const GITHUB = "https://github.com/Kart-ing";
const RECOMPRESS_DOI = "https://doi.org/10.5281/zenodo.20786357";

export const record: WorkRecord = {
  owner: {
    name: "Kartikey Pandey",
    role: "Founder, Karts",
    tagline:
      "Karts is a self-hosted development platform that brings AI coding agents, persistent dev environments and app hosting into one workspace.",
    links: [
      { label: "GitHub", url: GITHUB },
      { label: "LinkedIn", url: "https://www.linkedin.com/in/kartikeypandey2004/" },
      { label: "Email", url: "mailto:kartikeypandey.official@gmail.com" },
    ],
  },

  constellations: [
    { id: "building", label: "Building now" },
    { id: "agent-tools", label: "Agent tools" },
    { id: "research", label: "Research and patent" },
    { id: "hackathons", label: "Hackathon wins" },
    { id: "work", label: "Work" },
    { id: "leadership", label: "Leadership" },
    { id: "education", label: "Education" },
    { id: "more-projects", label: "More projects" },
  ],

  stars: [
    // ---------------------------------------------------------------- building
    {
      id: "karts",
      label: "Karts",
      constellation: "building",
      kind: "company",
      period: "2026",
      summary:
        "Karts is a self-hosted development platform that brings AI coding agents, persistent dev environments and app hosting into one workspace.",
      tags: [
        "karts",
        "self-hosted",
        "development platform",
        "dev environments",
        "app hosting",
        "platform",
        "company",
        "startup",
        "founder",
        "ide",
        "coding servers",
        "enterprise",
        "compliance",
        "building now",
        "current",
        "working on",
      ],
      links: [],
      start: "2026-08",
      weight: 3,
    },

    // ------------------------------------------------------------ agent tools
    {
      id: "multiverse",
      label: "Multiverse",
      constellation: "agent-tools",
      kind: "project",
      period: "2026",
      summary: "A speculative execution harness for AI agents.",
      tags: [
        "multiverse",
        "agents",
        "ai agents",
        "agent harness",
        "speculative execution",
        "tool calls",
        "sandbox",
        "fork",
        "replay",
        "branch predictor",
        "typescript",
        "opencode",
        "decision tree",
        "open source",
      ],
      links: [{ label: "GitHub", url: `${GITHUB}/multiverse` }],
      start: "2026-06",
      stack: ["TypeScript", "Bun", "ClickHouse", "Langfuse", "Composio"],
      repo: "Kart-ing/multiverse",
      media: [
        {
          kind: "image",
          src: "/media/multiverse.jpg",
          alt: "Terminal screenshot of the Multiverse TUI: a pixel-font multiverse banner above an Ask anything prompt.",
          width: 1200,
          height: 1002,
          credit: { label: "Devpost", url: "https://devpost.com/software/multiverse-xgqfrp" },
        },
      ],
      weight: 2,
    },
    {
      id: "pingpal",
      label: "PingPal",
      constellation: "agent-tools",
      kind: "project",
      period: "2026",
      summary:
        "Ambient messaging for CLI coders: see teammates' ASCII faces and send 90-char pings inside Claude Code.",
      tags: [
        "pingpal",
        "agents",
        "messaging",
        "chat",
        "pings",
        "claude code",
        "cli",
        "terminal",
        "npm",
        "mcp",
        "teammates",
        "typescript",
        "open source",
      ],
      links: [
        { label: "GitHub", url: `${GITHUB}/pingpal` },
        { label: "npm", url: "https://www.npmjs.com/package/pingpal" },
      ],
      start: "2026-06",
      stack: ["TypeScript", "Node.js", "pnpm", "MCP"],
      repo: "Kart-ing/pingpal",
      weight: 1,
    },
    {
      id: "hermes-offloader",
      label: "Hermes Offloader",
      constellation: "agent-tools",
      kind: "project",
      period: "2026",
      summary:
        "Offload work from your laptop to a cheap always-on server via /offload in Claude Code.",
      tags: [
        "hermes",
        "offloader",
        "offload",
        "handoff",
        "agents",
        "claude code",
        "server",
        "vps",
        "daemon",
        "systemd",
        "deepseek",
        "jobs",
        "orchestrator",
      ],
      links: [{ label: "GitHub (setup repo)", url: `${GITHUB}/hermes-offloader-setup` }],
      start: "2026-06",
      stack: ["Python", "Shell", "systemd", "SSH"],
      repo: "Kart-ing/hermes-offloader-setup",
      weight: 1,
    },

    // --------------------------------------------------------------- research
    {
      id: "recompress",
      label: "ReCompress preprint",
      constellation: "research",
      kind: "paper",
      period: "Jun 2026",
      summary:
        "ReCompress is a Zenodo preprint on query-aware LLM context compression beyond deletion, by Parth Sanjay Kshirsagar and Kartikey Pandey.",
      tags: [
        "recompress",
        "paper",
        "preprint",
        "research",
        "publication",
        "zenodo",
        "doi",
        "compression",
        "context compression",
        "prompt compression",
        "llm",
        "token company",
        "qwen",
        "lora",
        "distillation",
      ],
      links: [
        { label: "Preprint (Zenodo DOI)", url: RECOMPRESS_DOI },
        { label: "GitHub", url: `${GITHUB}/ReCompress` },
        { label: "Devpost", url: "https://devpost.com/software/re-compress" },
        { label: "Live demo", url: "https://demo-eight-olive-97.vercel.app" },
      ],
      start: "2026-06",
      stack: ["Python", "LoRA", "Qwen2.5-1.5B", "Modal"],
      repo: "Kart-ing/ReCompress",
      media: [
        {
          kind: "image",
          src: "/media/recompress.jpg",
          alt: "Line chart from the Re:Compress Devpost page: context tokens sent to the solver per conversation turn, for a naive growing history and for ReZero with the distilled model.",
          width: 1200,
          height: 720,
          credit: { label: "Devpost", url: "https://devpost.com/software/re-compress" },
        },
      ],
      weight: 2,
    },
    {
      id: "patent",
      label: "Indian Patent No. 558662",
      constellation: "research",
      kind: "patent",
      period: "Filed Oct 2020 · granted Jan 2025",
      summary:
        "Kartikey is the sole inventor and applicant on Indian Patent No. 558662, System and Method Providing Data Conversion.",
      tags: [
        "patent",
        "ip",
        "intellectual property",
        "india",
        "indian patent",
        "data conversion",
        "compression",
        "inventor",
        "high school",
        "granted",
      ],
      links: [
        {
          label: "IP India record (QuickCompany copy)",
          url: "https://www.quickcompany.in/patents/system-and-method-providing-data-conversion",
        },
      ],
      start: "2020-10",
      weight: 2,
    },

    // ------------------------------------------------------------- hackathons
    {
      id: "hackpsu-spring-2023",
      label: "SignEase",
      constellation: "hackathons",
      kind: "award",
      period: "Apr 2023",
      summary: "3rd Place at HackPSU Spring 2023 with SignEase.",
      tags: [
        "signease",
        "hackpsu",
        "penn state",
        "hackathon",
        "won",
        "award",
        "prize",
        "3rd place",
        "asl",
        "sign language",
        "banking",
        "2023",
      ],
      links: [{ label: "Devpost", url: "https://devpost.com/software/signease" }],
      start: "2023-04",
      media: [
        {
          kind: "image",
          src: "/media/hackpsu-spring-2023.jpg",
          alt: "SignEase logo: a pink waving hand above the name SignEase on a grid background.",
          width: 958,
          height: 769,
          credit: { label: "Devpost", url: "https://devpost.com/software/signease" },
        },
      ],
      weight: 1,
    },
    {
      id: "hackharvard-2023",
      label: "EyeSnap",
      constellation: "hackathons",
      kind: "award",
      period: "Oct 2023",
      summary:
        "Best Use of MATLAB at HackHarvard 2023 with EyeSnap, a diabetic retinopathy detection prototype.",
      tags: [
        "eyesnap",
        "hackharvard",
        "harvard",
        "hackathon",
        "won",
        "award",
        "prize",
        "matlab",
        "diabetic retinopathy",
        "healthcare",
        "medical",
        "computer vision",
        "cnn",
        "2023",
      ],
      links: [
        {
          label: "Devpost",
          url: "https://devpost.com/software/eyesnap-diabetic-retinopathy-detection-with-diascan",
        },
      ],
      start: "2023-10",
      stack: ["TensorFlow", "React Native", "Flask", "SQL"],
      media: [
        {
          kind: "image",
          src: "/media/hackharvard-2023.jpg",
          alt: "3D render of an orange cylindrical lens attachment on a red plate, from the EyeSnap Devpost page.",
          width: 302,
          height: 272,
          credit: { label: "Devpost", url: "https://devpost.com/software/eyesnap-diabetic-retinopathy-detection-with-diascan" },
        },
      ],
      weight: 1,
    },
    {
      id: "hackpsu-spring-2024",
      label: "DevSpot",
      constellation: "hackathons",
      kind: "award",
      period: "Mar 2024",
      summary: "Entrepreneurship Award at HackPSU Spring 2024 with DevSpot.",
      tags: [
        "devspot",
        "hackpsu",
        "penn state",
        "hackathon",
        "won",
        "award",
        "prize",
        "entrepreneurship",
        "2024",
      ],
      links: [{ label: "Devpost", url: "https://devpost.com/software/devspot" }],
      start: "2024-03",
      media: [
        {
          kind: "image",
          src: "/media/hackpsu-spring-2024.jpg",
          alt: "DevSpot logo: a white outlined emblem inside a circle on a brown background.",
          width: 1200,
          height: 1200,
          credit: { label: "Devpost", url: "https://devpost.com/software/devspot" },
        },
      ],
      weight: 1,
    },
    {
      id: "bitcamp-2024",
      label: "Moth Challenge",
      constellation: "hackathons",
      kind: "award",
      period: "Apr 2024",
      summary: "Best Cybersecurity Track Hack at Bitcamp 2024 with Moth Challenge.",
      tags: [
        "moth challenge",
        "bitcamp",
        "umd",
        "maryland",
        "hackathon",
        "won",
        "award",
        "prize",
        "cybersecurity",
        "security",
        "ctf",
        "puzzles",
        "cryptography",
        "steganography",
        "2024",
      ],
      links: [{ label: "Devpost", url: "https://devpost.com/software/moth-challenege" }],
      start: "2024-04",
      media: [
        {
          kind: "image",
          src: "/media/bitcamp-2024.jpg",
          alt: "Moth Challenge artwork: a green pixel-art moth over a striped circle on a black background.",
          width: 1024,
          height: 1024,
          credit: { label: "Devpost", url: "https://devpost.com/software/moth-challenege" },
        },
      ],
      weight: 1,
    },
    {
      id: "hackpsu-fall-2024",
      label: "Reality Rush",
      constellation: "hackathons",
      kind: "award",
      period: "Oct 2024",
      summary:
        "Snap AR Challenge winner and Best DEI Hack sponsored by Fidelity at HackPSU Fall 2024 with Reality Rush.",
      tags: [
        "reality rush",
        "hackpsu",
        "penn state",
        "hackathon",
        "won",
        "award",
        "prize",
        "snap",
        "snap ar challenge",
        "spectacles",
        "ar",
        "augmented reality",
        "fitness",
        "dei",
        "fidelity",
        "lens studio",
        "2024",
      ],
      links: [{ label: "Devpost", url: "https://devpost.com/software/reality-rush" }],
      start: "2024-10",
      stack: ["Lens Studio", "TypeScript", "Snap Spectacles"],
      media: [
        {
          kind: "image",
          src: "/media/hackpsu-fall-2024.jpg",
          alt: "Reality Rush wordmark in black over teal and lime shapes.",
          width: 1200,
          height: 1200,
          credit: { label: "Devpost", url: "https://devpost.com/software/reality-rush" },
        },
      ],
      weight: 1,
    },
    {
      id: "hackumass-xii",
      label: "VR Breadboard",
      constellation: "hackathons",
      kind: "award",
      period: "Nov 2024",
      summary: "Best AR/VR Hack at HackUMass XII with VR Breadboard.",
      tags: [
        "vr breadboard",
        "circuit simulator",
        "hackumass",
        "umass",
        "hackathon",
        "won",
        "award",
        "prize",
        "vr",
        "ar",
        "virtual reality",
        "circuits",
        "electronics",
        "meta quest",
        "2024",
      ],
      links: [{ label: "Devpost", url: "https://devpost.com/software/circuit-simulator" }],
      start: "2024-11",
      stack: ["Meta Quest 3"],
      media: [
        {
          kind: "image",
          src: "/media/hackumass-xii.jpg",
          alt: "Screenshot of the VR Breadboard simulator: a breadboard with logic gate buttons, four inputs, VCC and GND wires and nine output pins.",
          width: 1200,
          height: 635,
          credit: { label: "Devpost", url: "https://devpost.com/software/circuit-simulator" },
        },
      ],
      weight: 1,
    },
    {
      id: "mhacks-2025",
      label: "SoundSage",
      constellation: "hackathons",
      kind: "award",
      period: "Sep 2025",
      summary:
        "Best Use of MemryX Edge AI Accelerator at MHacks 2025 with SoundSage, a one-person entry.",
      tags: [
        "soundsage",
        "mhacks",
        "michigan",
        "hackathon",
        "won",
        "award",
        "prize",
        "memryx",
        "edge ai",
        "npu",
        "audio",
        "music",
        "alone",
        "2025",
      ],
      links: [{ label: "Devpost", url: "https://devpost.com/software/soundsage" }],
      start: "2025-09",
      stack: ["MemryX"],
      media: [
        {
          kind: "image",
          src: "/media/mhacks-2025.jpg",
          alt: "SoundSage logo: a teal brain outline between audio waveforms on a navy background.",
          width: 1024,
          height: 1024,
          credit: { label: "Devpost", url: "https://devpost.com/software/soundsage" },
        },
      ],
      weight: 1,
    },
    {
      id: "calhacks-12",
      label: "AgentOverflow",
      constellation: "hackathons",
      kind: "award",
      period: "Oct 2025",
      summary:
        "Elastic: Best use of the Elastic Agent Builder on a Serverless instance, at Cal Hacks 12.0 with AgentOverflow.",
      tags: [
        "agentoverflow",
        "cal hacks",
        "calhacks",
        "berkeley",
        "hackathon",
        "won",
        "award",
        "prize",
        "elastic",
        "agent builder",
        "serverless",
        "agents",
        "stack overflow",
        "2025",
      ],
      links: [
        { label: "Devpost", url: "https://devpost.com/software/agentoverflow" },
        { label: "GitHub", url: `${GITHUB}/agentoverflow` },
      ],
      start: "2025-10",
      stack: ["TypeScript", "Node.js", "Elasticsearch"],
      repo: "Kart-ing/agentoverflow",
      media: [
        {
          kind: "image",
          src: "/media/calhacks-12.jpg",
          alt: "AgentOverflow logo: a speech bubble holding orange stacked bars, above the name AgentOverflow.",
          width: 1024,
          height: 1024,
          credit: { label: "Devpost", url: "https://devpost.com/software/agentoverflow" },
        },
      ],
      weight: 1,
    },
    {
      id: "berkeley-ai-hackathon-2026",
      label: "Re:Compress",
      constellation: "hackathons",
      kind: "award",
      period: "Jun 2026",
      summary:
        "Best Compression Model for The Token Company at the UC Berkeley AI Hackathon 2026 with Re:Compress.",
      tags: [
        "re:compress",
        "recompress",
        "uc berkeley ai hackathon",
        "berkeley",
        "hackathon",
        "won",
        "award",
        "prize",
        "token company",
        "compression",
        "recent",
        "2026",
      ],
      links: [
        { label: "Devpost", url: "https://devpost.com/software/re-compress" },
        { label: "GitHub", url: `${GITHUB}/ReCompress` },
      ],
      start: "2026-06",
      stack: ["Python", "LoRA", "Qwen2.5-1.5B"],
      repo: "Kart-ing/ReCompress",
      media: [
        {
          kind: "image",
          src: "/media/berkeley-ai-hackathon-2026.jpg",
          alt: "Re:Compress logo: a document with a question mark funnelled by two arrows into a small block, above the name RE:COMPRESS.",
          width: 1200,
          height: 654,
          credit: { label: "Devpost", url: "https://devpost.com/software/re-compress" },
        },
      ],
      weight: 2,
    },
    {
      id: "compiled-11",
      label: "Cited",
      constellation: "hackathons",
      kind: "award",
      period: "Jul 24, 2026",
      summary:
        "Hexclave award ($1,000) at c0mpiled-11, the YC Startup School Hackathon hosted by Transpose, with Cited.",
      tags: [
        "cited",
        "c0mpiled",
        "compiled",
        "c0mpiled-11",
        "yc",
        "y combinator",
        "startup school",
        "transpose",
        "hexclave",
        "hackathon",
        "won",
        "award",
        "prize",
        "recent",
        "2026",
      ],
      links: [
        {
          label: "Organizer write-up",
          url: "https://www.compiled.sh/articles/c0mpiled-11-yc-startup-school-hackathon",
        },
      ],
      start: "2026-07",
      weight: 2,
    },
    {
      id: "compiled-13",
      label: "Swiper No Swiping",
      constellation: "hackathons",
      kind: "award",
      period: "Jul 25, 2026",
      summary:
        "Hexclave award ($1,000) at c0mpiled-13, Startup School Hackathon II hosted by Transpose, with Swiper No Swiping.",
      tags: [
        "swiper no swiping",
        "c0mpiled",
        "compiled",
        "c0mpiled-13",
        "yc",
        "y combinator",
        "startup school",
        "transpose",
        "hexclave",
        "hackathon",
        "won",
        "award",
        "prize",
        "recent",
        "2026",
      ],
      links: [
        {
          label: "Organizer write-up",
          url: "https://www.compiled.sh/articles/c0mpiled-13-startup-school-hackathon-ii",
        },
      ],
      start: "2026-07",
      weight: 2,
    },
    {
      id: "zero-human-company-hackathon",
      label: "AdLayer",
      constellation: "hackathons",
      kind: "award",
      period: "Aug 15, 2026",
      summary:
        "3rd place in Best use of Render at The World's First Zero Human Company Hackathon by Terac, with AdLayer.",
      tags: [
        "adlayer",
        "terac",
        "zero human company",
        "render",
        "hackathon",
        "won",
        "award",
        "prize",
        "3rd place",
        "llms.txt",
        "ads",
        "advertising",
        "answer layer",
        "12x",
        "how many",
        "hackathon winner",
        "latest",
        "recent",
        "2026",
      ],
      links: [{ label: "GitHub", url: `${GITHUB}/adlayer` }],
      start: "2026-08",
      stack: ["TypeScript", "Render"],
      repo: "Kart-ing/adlayer",
      weight: 2,
    },

    // ------------------------------------------------------------------- work
    {
      id: "cara",
      label: "Cara",
      constellation: "work",
      kind: "role",
      period: "Jun 2026 – present",
      summary: "Member of Technical Staff at Cara, San Francisco Bay Area, since June 2026.",
      tags: [
        "cara",
        "job",
        "work",
        "role",
        "current",
        "now",
        "member of technical staff",
        "mts",
        "san francisco",
        "bay area",
        "employer",
      ],
      links: [],
      start: "2026-06",
      weight: 1,
    },
    {
      id: "raya-health",
      label: "Raya Health",
      constellation: "work",
      kind: "role",
      period: "Feb 2026 – May 2026",
      summary: "Founding Engineer at Raya Health, part of the HF0 W26 residency batch.",
      tags: [
        "raya",
        "raya health",
        "founding engineer",
        "hf0",
        "residency",
        "job",
        "work",
        "role",
        "startup",
        "health",
        "2026",
      ],
      links: [],
      start: "2026-02",
      weight: 1,
    },
    {
      id: "coldstart",
      label: "ColdStart",
      constellation: "work",
      kind: "role",
      period: "Jan 2025 – May 2025",
      summary: "Software Engineer Intern at ColdStart in State College, PA.",
      tags: [
        "coldstart",
        "intern",
        "internship",
        "software engineer",
        "job",
        "work",
        "role",
        "state college",
        "2025",
      ],
      links: [],
      start: "2025-01",
      weight: 1,
    },
    {
      id: "intel",
      label: "Intel Corporation",
      constellation: "work",
      kind: "role",
      period: "Aug 2020 – Jul 2021",
      summary:
        "Internship Trainee, then Apprentice, at Intel Corporation, building ML pipelines and computer-vision systems.",
      tags: [
        "intel",
        "apprentice",
        "internship trainee",
        "intern",
        "job",
        "work",
        "role",
        "machine learning",
        "ml",
        "tensorflow",
        "pytorch",
        "opencv",
        "bert",
        "nlp",
        "aws",
        "docker",
        "computer vision",
        "2020",
        "2021",
      ],
      links: [],
      start: "2020-08",
      stack: ["Python", "TensorFlow", "PyTorch", "OpenCV", "Docker", "AWS"],
      weight: 1,
    },
    {
      id: "lunar-autonomy-challenge",
      label: "NASA Lunar Autonomy Challenge",
      constellation: "work",
      kind: "role",
      period: "Nov 2024 – Jan 2025",
      summary:
        "Machine learning on a team in the NASA Lunar Autonomy Challenge, run by Johns Hopkins APL.",
      tags: [
        "nasa",
        "lunar",
        "moon",
        "lunar autonomy challenge",
        "johns hopkins",
        "jhu",
        "apl",
        "robotics",
        "rover",
        "slam",
        "carla",
        "simulation",
        "machine learning",
        "lsii",
        "space",
      ],
      links: [],
      start: "2024-11",
      stack: ["Python", "CARLA", "SLAM"],
      weight: 1,
    },
    {
      id: "snap-accelerator",
      label: "Snap Spectacles Student Accelerator",
      constellation: "work",
      kind: "role",
      summary:
        "Secured $25,000+ in funding through Snap's Spectacles Student Accelerator and led AR/AI development.",
      tags: [
        "snap",
        "spectacles",
        "accelerator",
        "funding",
        "25k",
        "ar",
        "augmented reality",
        "lens studio",
        "typescript",
        "node.js",
        "cloud sync",
        "project elementals",
        "team virtus",
        "motion sickness",
      ],
      links: [],
      stack: ["Lens Studio", "TypeScript", "Node.js"],
      weight: 1,
    },

    // ------------------------------------------------------------- leadership
    {
      id: "psu-hackathon-team",
      label: "Penn State Collegiate Hackathon Team",
      constellation: "leadership",
      kind: "community",
      period: "Aug 2024 – Dec 2025",
      summary:
        "Founder & President of the Penn State Collegiate Hackathon Team, which grew to 27+ members and lifted Penn State's national hackathon rank from #185 to #74 in one year.",
      tags: [
        "penn state",
        "psu",
        "hackathon team",
        "founder",
        "president",
        "leadership",
        "community",
        "team",
        "ranking",
        "rank",
        "sponsorships",
        "workshops",
        "next.js",
        "graphql",
        "mentoring",
      ],
      links: [],
      start: "2024-08",
      weight: 2,
    },
    {
      id: "gdsc-psu",
      label: "GDSC at Penn State",
      constellation: "leadership",
      kind: "community",
      period: "Jan 2023 – May 2025",
      summary:
        "Technical Lead, then President, of GDSC at Penn State, building a 200+ student developer community.",
      tags: [
        "gdsc",
        "google developer student club",
        "google",
        "penn state",
        "psu",
        "president",
        "technical lead",
        "leadership",
        "community",
        "students",
        "club",
      ],
      links: [],
      start: "2023-01",
      weight: 1,
    },

    // -------------------------------------------------------------- education
    {
      id: "penn-state",
      label: "Penn State University",
      constellation: "education",
      kind: "education",
      period: "2022 – 2026",
      summary:
        "B.S. Computer Science with a Minor in Entrepreneurship at Penn State University, 2022 to 2026.",
      tags: [
        "penn state",
        "psu",
        "education",
        "school",
        "university",
        "college",
        "degree",
        "bs",
        "computer science",
        "cs",
        "entrepreneurship",
        "minor",
        "study",
        "studied",
      ],
      links: [],
      weight: 1,
    },

    // ---------------------------------------------------------- more projects
    {
      id: "acrn",
      label: "ACRN",
      constellation: "more-projects",
      kind: "project",
      period: "2026",
      summary: "Brand site for a hacker house: botanical-press meets terminal.",
      tags: [
        "acrn",
        "hacker house",
        "website",
        "site",
        "design",
        "static site",
        "material design",
        "typography",
        "frontend",
        "vercel",
      ],
      links: [{ label: "Live site", url: "https://acrn.space" }],
      stack: ["HTML", "CSS", "JavaScript", "Vercel"],
      weight: 1,
    },
    {
      id: "token-company-prd",
      label: "Token Company PRD",
      constellation: "more-projects",
      kind: "project",
      period: "Jun 2026",
      summary: "The benchmarking research brief behind ReCompress, published on GitHub.",
      tags: [
        "token company",
        "prd",
        "research brief",
        "benchmark",
        "benchmarking",
        "swe-bench",
        "recompress",
        "compression",
        "plan",
      ],
      links: [{ label: "GitHub", url: `${GITHUB}/token-company-prd` }],
      start: "2026-06",
      repo: "Kart-ing/token-company-prd",
      weight: 1,
    },
  ],

  facets: [
    // ---------------------------------------------------------------- building
    {
      id: "karts.what",
      starId: "karts",
      text: "Karts is a self-hosted development platform that brings AI coding agents, persistent dev environments and app hosting into one workspace.",
    },
    {
      id: "karts.capabilities",
      starId: "karts",
      text: "Teams can coordinate coding agents, give each developer or branch its own services and data, and check environments against production.",
    },
    {
      id: "karts.operations",
      starId: "karts",
      text: "Teams can catch outdated branches, simulate load, and publish applications on their own domains, all on infrastructure they control.",
    },
    {
      id: "karts.why",
      starId: "karts",
      text: "Karts helps startups build and ship software without having to assemble and maintain their own internal development platform.",
    },
    {
      id: "karts.founder",
      starId: "karts",
      text: "Kartikey is the founder of Karts.",
    },

    // ------------------------------------------------------------ agent tools
    {
      id: "multiverse.what",
      starId: "multiverse",
      text: "The branch predictor, but for tool calls: fork into parallel sandboxed futures, commit one winner atomically, replay deterministically.",
    },
    {
      id: "multiverse.how",
      starId: "multiverse",
      text: "A fork of OpenCode, the open source AI coding agent, with a decision tree mode that explores 5 parallel approaches per step: Direct, Modular, Minimal, Robust and Creative.",
    },
    {
      id: "multiverse.replay",
      starId: "multiverse",
      text: "Each approach is scored from 0 to 100 against the step's success metric, and only the winning branch advances to the next step.",
    },
    {
      id: "multiverse.stack",
      starId: "multiverse",
      text: "TypeScript on Bun, with Langfuse branch-level tracing, ClickHouse tree-state persistence and Composio tool execution. Built for the Harness Engineering Hackathon in June 2026.",
    },
    {
      id: "pingpal.what",
      starId: "pingpal",
      text: "Ambient messaging for CLI coders: see teammates' ASCII faces and send 90-char pings inside Claude Code.",
    },
    {
      id: "pingpal.how",
      starId: "pingpal",
      text: "A daemon, CLI, MCP server and relay in a TypeScript/Node pnpm monorepo; pings surface inside Claude Code sessions through hooks and MCP, with live presence.",
    },
    {
      id: "pingpal.network",
      starId: "pingpal",
      text: "Pings are end-to-end encrypted, so the relay cannot read them; mDNS auto-discovers same-network peers and falls back to a self-hostable relay for remote contacts.",
    },
    {
      id: "pingpal.npm",
      starId: "pingpal",
      text: "Published on npm (npm i -g pingpal) and works across Claude Code, OpenCode and Codex.",
      source: { label: "npm", url: "https://www.npmjs.com/package/pingpal" },
    },
    {
      id: "hermes-offloader.what",
      starId: "hermes-offloader",
      text: "Offload work from your laptop to a cheap always-on server via /offload in Claude Code.",
    },
    {
      id: "hermes-offloader.how",
      starId: "hermes-offloader",
      text: "A /handoff skill slices the conversation into a task DAG plus context brief and ships a job bundle over SSH to a daemon, which runs a worker per task on a cheaper model (DeepSeek).",
    },
    {
      id: "hermes-offloader.setup",
      starId: "hermes-offloader",
      text: "Public setup repo: \"Set up the Hermes job-offload pipeline (Mac-side /handoff dispatcher + VPS-side daemon) on your own VPS.\" The main repo is private.",
    },
    {
      id: "hermes-offloader.deploy",
      starId: "hermes-offloader",
      text: "Deployed as systemd services on a personal server: a Python (stdlib-only) orchestrator, shell, SSH/scp and NDJSON, returning status JSON and git-diff patches.",
    },

    // --------------------------------------------------------------- research
    {
      id: "recompress.preprint",
      starId: "recompress",
      text: "\"ReCompress: Query-Aware Rewriting and Tiered Memory for Efficient LLM Context Compression\", a Zenodo preprint of June 21, 2026, by Parth Sanjay Kshirsagar and Kartikey Pandey.",
      source: { label: "Preprint (Zenodo DOI)", url: RECOMPRESS_DOI },
    },
    {
      id: "recompress.method",
      starId: "recompress",
      text: "Query-aware compression beyond deletion: a DeepSeek teacher distilled into a Qwen2.5-1.5B + LoRA student rewrites context to drop passages irrelevant to the question.",
      source: { label: "GitHub", url: `${GITHUB}/ReCompress` },
    },
    {
      id: "recompress.result",
      starId: "recompress",
      text: "The 1.5B student compresses HotpotQA context to about 3.5% of its tokens and still answers correctly, keeping the answer-bearing span where deletion truncates it.",
      source: { label: "Preprint (Zenodo DOI)", url: RECOMPRESS_DOI },
    },
    {
      id: "recompress.multiturn",
      starId: "recompress",
      text: "Its \"Re:Zero\" tiered memory keeps a 12-turn conversation flat at about 184 tokens versus a naive 1,482, an 8.1x reduction.",
      source: { label: "GitHub", url: `${GITHUB}/ReCompress` },
    },
    {
      id: "patent.what",
      starId: "patent",
      text: "Indian Patent No. 558662, \"System and Method Providing Data Conversion\", application 202041040194.",
    },
    {
      id: "patent.inventor",
      starId: "patent",
      text: "Kartikey is the sole inventor and applicant.",
    },
    {
      id: "patent.timeline",
      starId: "patent",
      text: "Filed in October 2020, during high school; the grant was published on January 31, 2025.",
    },
    {
      id: "patent.claims",
      starId: "patent",
      text: "It describes AI that filters input such as audio or text and outputs it compressed.",
    },

    // ------------------------------------------------------------- hackathons
    {
      id: "hackpsu-spring-2023.prize",
      starId: "hackpsu-spring-2023",
      text: "Won 3rd Place at HackPSU Spring 2023 (April 2023) with SignEase.",
    },
    {
      id: "hackpsu-spring-2023.what",
      starId: "hackpsu-spring-2023",
      text: "Devpost tagline: \"Our project incorporates ASL sign language translation in the banking system, promoting financial inclusion and empowering the deaf and hard-of-hearing community.\"",
    },
    {
      id: "hackharvard-2023.prize",
      starId: "hackharvard-2023",
      text: "Won Best Use of MATLAB at HackHarvard 2023 (October 2023) with EyeSnap.",
    },
    {
      id: "hackharvard-2023.what",
      starId: "hackharvard-2023",
      text: "EyeSnap is a diabetic retinopathy detection prototype: a CNN screens retinal images inside a React Native app with offline processing.",
    },
    {
      id: "hackharvard-2023.stack",
      starId: "hackharvard-2023",
      text: "Built with computer vision, TensorFlow, Flask and SQL.",
    },
    {
      id: "hackpsu-spring-2024.prize",
      starId: "hackpsu-spring-2024",
      text: "Won the Entrepreneurship Award at HackPSU Spring 2024 (March 2024) with DevSpot.",
    },
    {
      id: "hackpsu-spring-2024.what",
      starId: "hackpsu-spring-2024",
      text: "Devpost tagline: \"DevSpot: Transforming hackathons with AI-driven insights. Validate ideas, find unique resources, and explore similar projects—all in one platform.\"",
    },
    {
      id: "bitcamp-2024.prize",
      starId: "bitcamp-2024",
      text: "Won Best Cybersecurity Track Hack at Bitcamp 2024 (April 2024) with Moth Challenge.",
    },
    {
      id: "bitcamp-2024.what",
      starId: "bitcamp-2024",
      text: "From the Devpost tagline: \"a dynamic cyber security puzzle platform. Sharpen skills through steganography, cryptography, and more.\"",
    },
    {
      id: "hackpsu-fall-2024.prize",
      starId: "hackpsu-fall-2024",
      text: "Won the Snap AR Challenge and Best DEI Hack sponsored by Fidelity at HackPSU Fall 2024 (October 2024) with Reality Rush.",
    },
    {
      id: "hackpsu-fall-2024.what",
      starId: "hackpsu-fall-2024",
      text: "A Snap Spectacles AR fitness trainer: Lens Studio's ML Kit tracks pose in real time for live form correction, with a gesture UI on the Spectacles Hand Tracking API.",
    },
    {
      id: "hackpsu-fall-2024.role",
      starId: "hackpsu-fall-2024",
      text: "Kartikey was the lead AR developer; built with Lens Studio and TypeScript.",
    },
    {
      id: "hackumass-xii.prize",
      starId: "hackumass-xii",
      text: "Won Best AR/VR Hack at HackUMass XII (November 2024) with VR Breadboard.",
    },
    {
      id: "hackumass-xii.what",
      starId: "hackumass-xii",
      text: "Devpost tagline: \"Interactive VR based realistic breadboard, wires, and components for students to build and test circuits in an engaging, risk-free virtual lab, with a Meta Quest 3.\"",
    },
    {
      id: "mhacks-2025.prize",
      starId: "mhacks-2025",
      text: "Won Best Use of MemryX Edge AI Accelerator at MHacks 2025 (September 2025) with SoundSage.",
    },
    {
      id: "mhacks-2025.team",
      starId: "mhacks-2025",
      text: "SoundSage was a one-person entry: Kartikey built it alone.",
    },
    {
      id: "mhacks-2025.what",
      starId: "mhacks-2025",
      text: "From the Devpost tagline: \"Instantly identifies genres and auto-optimizes EQ through dual AI models. Runs locally on MemryX NPU hardware\".",
    },
    {
      id: "calhacks-12.prize",
      starId: "calhacks-12",
      text: "Won \"Elastic: Best use of the Elastic Agent Builder on a Serverless instance\" at Cal Hacks 12.0 (October 2025) with AgentOverflow.",
    },
    {
      id: "calhacks-12.what",
      starId: "calhacks-12",
      text: "Devpost tagline: \"Stack Overflow 2.0: break the prompt spiral-> jump straight to the proven fix.\"",
    },
    {
      id: "berkeley-ai-hackathon-2026.prize",
      starId: "berkeley-ai-hackathon-2026",
      text: "Won Best Compression Model for The Token Company at the UC Berkeley AI Hackathon 2026 (June 20-21, 2026) with Re:Compress.",
    },
    {
      id: "berkeley-ai-hackathon-2026.what",
      starId: "berkeley-ai-hackathon-2026",
      text: "Devpost tagline: \"A query-aware rewriting layer that extends compression into the regime deletion can't reach — distilled into a 1.5B model, then carried into multi-turn conversations.\"",
    },
    {
      id: "berkeley-ai-hackathon-2026.paper",
      starId: "berkeley-ai-hackathon-2026",
      text: "The same work became the ReCompress preprint on Zenodo (June 21, 2026).",
      source: { label: "Preprint (Zenodo DOI)", url: RECOMPRESS_DOI },
    },
    {
      id: "compiled-11.prize",
      starId: "compiled-11",
      text: "Won the Hexclave award ($1,000) at c0mpiled-11, the YC Startup School Hackathon, with Cited.",
    },
    {
      id: "compiled-11.event",
      starId: "compiled-11",
      text: "c0mpiled-11 was hosted by Transpose on July 24, 2026; the organizer's write-up lists Cited among the prize winners.",
    },
    {
      id: "compiled-13.prize",
      starId: "compiled-13",
      text: "Won the Hexclave award ($1,000) at c0mpiled-13, Startup School Hackathon II, with Swiper No Swiping.",
    },
    {
      id: "compiled-13.event",
      starId: "compiled-13",
      text: "c0mpiled-13 was hosted by Transpose on July 25, 2026; the organizer's write-up lists Swiper No Swiping among the prize winners.",
    },
    {
      id: "zero-human-company-hackathon.prize",
      starId: "zero-human-company-hackathon",
      text: "Won 3rd place in Best use of Render at The World's First Zero Human Company Hackathon by Terac (August 15, 2026) with AdLayer.",
    },
    {
      id: "zero-human-company-hackathon.what",
      starId: "zero-human-company-hackathon",
      text: "The ad network for the answer layer: disclosed placements in llms.txt, and measurement of whether the label survives the model.",
    },
    {
      id: "zero-human-company-hackathon.count",
      starId: "zero-human-company-hackathon",
      text: "Kartikey is a 12x hackathon winner; AdLayer (August 2026) was the twelfth win.",
    },

    // ------------------------------------------------------------------- work
    {
      id: "cara.role",
      starId: "cara",
      text: "Member of Technical Staff at Cara since June 2026.",
    },
    {
      id: "cara.where",
      starId: "cara",
      text: "Based in the San Francisco Bay Area.",
    },
    {
      id: "raya-health.role",
      starId: "raya-health",
      text: "Founding Engineer at Raya Health from February to May 2026, in the HF0 W26 residency batch.",
    },
    {
      id: "raya-health.built",
      starId: "raya-health",
      text: "Built Raya Health from the ground up and shipped product end to end across full-stack, infrastructure and AI.",
    },
    {
      id: "coldstart.role",
      starId: "coldstart",
      text: "Software Engineer Intern at ColdStart, January to May 2025, in State College, PA.",
    },
    {
      id: "coldstart.work",
      starId: "coldstart",
      text: "A software engineering internship contributing to product development and full-stack engineering.",
    },
    {
      id: "intel.role",
      starId: "intel",
      text: "Internship Trainee at Intel Corporation from August 2020 to May 2021, then Apprentice from May to July 2021.",
    },
    {
      id: "intel.pipeline",
      starId: "intel",
      text: "Built an ML training pipeline (TensorFlow, Python, Docker, AWS) that cut model deployment time by 33%, from 3 days to 2.",
    },
    {
      id: "intel.vision",
      starId: "intel",
      text: "Built a computer-vision chip-defect detector (OpenCV, PyTorch) with 97% accuracy on 100,000+ test images.",
    },
    {
      id: "intel.nlp",
      starId: "intel",
      text: "Built a BERT-based classifier handling 1,000+ technical specs a day at 90% accuracy.",
    },
    {
      id: "lunar-autonomy-challenge.role",
      starId: "lunar-autonomy-challenge",
      text: "Machine learning on a NASA Lunar Autonomy Challenge team, run by Johns Hopkins APL, from November 2024 to January 2025.",
    },
    {
      id: "lunar-autonomy-challenge.what",
      starId: "lunar-autonomy-challenge",
      text: "Autonomous lunar robotics: navigation, excavation and resource utilization, using CARLA simulation and SLAM.",
    },
    {
      id: "lunar-autonomy-challenge.lsii",
      starId: "lunar-autonomy-challenge",
      text: "The work supported NASA's Lunar Surface Innovation Initiative (LSII).",
    },
    {
      id: "snap-accelerator.funding",
      starId: "snap-accelerator",
      text: "Secured $25,000+ in funding through the Snap Spectacles Student Accelerator.",
    },
    {
      id: "snap-accelerator.role",
      starId: "snap-accelerator",
      text: "Led AR/AI development with TypeScript, Node.js and real-time cloud sync.",
    },
    {
      id: "snap-accelerator.elementals",
      starId: "snap-accelerator",
      text: "Project Elementals: a multiplayer AR game on Spectacles where players bend elements in one shared world, synced in real time across devices; Kartikey was lead AR developer.",
    },
    {
      id: "snap-accelerator.motion",
      starId: "snap-accelerator",
      text: "Also built a stabilization approach that reduces motion sickness during AR use in moving environments, aimed at comfortable extended wear.",
    },

    // ------------------------------------------------------------- leadership
    {
      id: "psu-hackathon-team.role",
      starId: "psu-hackathon-team",
      text: "Founder & President of the Penn State Collegiate Hackathon Team, August 2024 to December 2025.",
    },
    {
      id: "psu-hackathon-team.growth",
      starId: "psu-hackathon-team",
      text: "Grew the team to 27+ members.",
    },
    {
      id: "psu-hackathon-team.rank",
      starId: "psu-hackathon-team",
      text: "Lifted Penn State's national hackathon rank from #185 to #74 within one year.",
    },
    {
      id: "psu-hackathon-team.program",
      starId: "psu-hackathon-team",
      text: "Built a dual-track program, secured national sponsorships, and ran workshops on Next.js, GraphQL and automation engineering.",
    },
    {
      id: "gdsc-psu.role",
      starId: "gdsc-psu",
      text: "Technical Lead of GDSC at Penn State from January 2023 to August 2024, then President from August 2024 to May 2025.",
    },
    {
      id: "gdsc-psu.community",
      starId: "gdsc-psu",
      text: "Built a 200+ student developer community focused on software engineering, AI/ML and cloud.",
    },

    // -------------------------------------------------------------- education
    {
      id: "penn-state.degree",
      starId: "penn-state",
      text: "B.S. Computer Science, Minor in Entrepreneurship, Penn State University, 2022 to 2026.",
    },
    {
      id: "penn-state.focus",
      starId: "penn-state",
      text: "Focus on software engineering, AI/ML and systems.",
    },

    // ---------------------------------------------------------- more projects
    {
      id: "acrn.what",
      starId: "acrn",
      text: "Brand site and member directory for a hacker house, designed and built by Kartikey to feel hand-made rather than templated.",
    },
    {
      id: "acrn.design",
      starId: "acrn",
      text: "A bespoke Material Design 3 color system themed on soil, moss, acorn, fern and clay, with three typefaces: Fraunces, Newsreader and JetBrains Mono.",
    },
    {
      id: "acrn.build",
      starId: "acrn",
      text: "No framework: a hand-written index of about 35KB with full OG/SEO meta and 8 member profiles, in HTML, CSS and vanilla JS on Vercel.",
    },
    {
      id: "token-company-prd.what",
      starId: "token-company-prd",
      text: "The benchmarking research brief behind ReCompress.",
    },
    {
      id: "token-company-prd.desc",
      starId: "token-company-prd",
      text: "Repo description: \"The Token Company — UC Berkeley AI Hackathon 2026 PRD: a LoRA fine-tuned code-context compressor proven on held-out SWE-bench (same bug found, far fewer tokens).\"",
    },
  ],
};
